In [3]:
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()

In [4]:
X = housing['data']
y = housing['target']

In [6]:
X.shape

(20640, 8)

In [8]:
import numpy as np

W = np.random.randn(X.shape[1])
b = np.random.randn()
W, b

(array([-1.20793698, -0.51257044, -0.52230247,  0.51501047, -0.24700104,
         0.63067048, -0.82726192,  0.60182829]),
 0.3030120683652575)

In [9]:
print("First Input:", X[0])
print("First Weight:", W[0])
print("Bias:", b)

First Input: [   8.3252       41.            6.98412698    1.02380952  322.
    2.55555556   37.88       -122.23      ]
First Weight: -1.2079369796374166
Bias: 0.3030120683652575


In [10]:
def heaviside(x):
    return 1 if x >= 0 else 0

In [14]:
x = X[0:5]

In [18]:
x.shape

(5, 8)

In [20]:
(x @ W).shape

(5,)

In [ ]:
z = x @ W + b

y = np.heaviside(z, 0)

print("Output:", y)

Output: [0. 0. 0. 0. 0.]


In [33]:
def model(X):
    z = X @ W + b
    y = np.heaviside(z, 0)
    return y

print("Model Output:", model(x))

Model Output: [0. 0. 0. 0. 0.]


In [39]:
X = housing['data'][:, :2]
y = housing['target']

In [40]:
X

array([[ 8.3252, 41.    ],
       [ 8.3014, 21.    ],
       [ 7.2574, 52.    ],
       ...,
       [ 1.7   , 17.    ],
       [ 1.8672, 18.    ],
       [ 2.3886, 16.    ]], shape=(20640, 2))

In [95]:
np.random.seed(42)

def MLP_old(X):
    W1 = np.random.randn(X.shape[1])
    b1 = np.random.randn()
    z1 = X @ W1 + b1
    y1 = np.heaviside(z1, 0)

    # Hidden layer
    W2 = np.random.randn(X.shape[1])
    b2 = np.random.randn()
    z2 = X @ W2 + b2    
    y2 = np.heaviside(z2, 0)

    # Hidden layer
    W3 = np.random.randn(X.shape[1])
    b3 = np.random.randn()
    z3 = X @ W3 + b3
    y3 = np.heaviside(z3, 0)

    return np.array([y1, y2, y3]).T


def MLP(X):
    # shape of X: (N, m)
    # shape of W: (m, 3)
    #  shape of b: (3, )
    W = np.random.randn(X.shape[1], 3)
    b = np.random.randn(3)
    z = X @ W + b
    y = np.heaviside(z, 0)

    return y

x = X[:8]

y_old = MLP_old(x)
y_new = MLP(x)

y_old, y_new

(array([[0., 1., 1.],
        [1., 1., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]]))

In [103]:
np.random.seed(42)

def MLP(x, number_of_layers: int = 3):
    W = np.random.randn(X.shape[1], number_of_layers)
    b = np.random.randn(number_of_layers)
    z = X @ W + b
    y = np.heaviside(z, 0)

    return y


X = housing['data'][:3]
y = MLP(X, number_of_layers=5)
y

array([[1., 1., 1., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [105]:
class MLP_Class:
    def __init__(self, input_size: int = 3, output_size: int = 3):
        self.input_size = input_size
        self.output_size = output_size

    def predict(self, X):
        W = np.random.randn(self.input_size, self.output_size)
        b = np.random.randn(self.output_size)
        z = X @ W + b
        y = np.heaviside(z, 0)

        return y
    
    @property
    def parameter_size(self):
        return (self.input_size + 1) * self.output_size
    
mlp = MLP_Class(784, 10)
mlp.parameter_size

7850

In [109]:
X.shape

(3, 8)

In [ ]:
class FNN: #Feedforward Neural Network
    def __init__(self, input_size: int, hidden_sizes: list[int], output_size: int):
        self.input_size = input_size
        self.hidden_sizes = hidden_sizes
        self.output_size = output_size

    def fit(self, X, y):
        layer_sizes = [self.input_size] + self.hidden_sizes + [self.output_size]
        Ws = []
        bs = []

        for size1, size2 in zip(layer_sizes, layer_sizes[1:]):
            W = np.random.randn(size1, size2)
            b = np.random.randn(size2)
            Ws.append(W)
            bs.append(b)

        # And we have to fit them

    def predict(self, X):
        layer_sizes = [self.input_size] + self.hidden_sizes + [self.output_size]

        h_in = X
        for size1, size2 in zip(layer_sizes, layer_sizes[1:]):
            W = np.random.randn(size1, size2)
            b = np.random.randn(size2)
            z = h_in @ W + b
            h_out = np.heaviside(z, 0)
            h_in = h_out

        return h_out


    @property
    def parameter_size(self):
        return (self.input_size + 1) * self.hidden_sizes[0] + sum((h + 1) * n for h, n in zip(self.hidden_sizes[:-1], self.hidden_sizes[1:])) + (self.hidden_sizes[-1] + 1) * self.output_size
    

nn = FNN(input_size=8, hidden_sizes=[6, 4, 2, 7], output_size=10)
nn.fit(X, y)
nn.predict(X)

array([[1., 1., 0., 0., 0., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 1., 1., 1., 1., 1.]])

In [116]:
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [123]:
X = housing['data']
y = housing['target']

mlp_reg = MLPRegressor(hidden_layer_sizes=(10, 5), max_iter=500, random_state=42)
mlp_reg.fit(X, y)

y = mlp_reg.predict(X)

In [126]:
pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('mlp_reg', MLPRegressor(hidden_layer_sizes=(58, 60, 40), max_iter=500, random_state=42))
])

In [127]:
pipe.fit(X, y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('mlp_reg',
                 MLPRegressor(hidden_layer_sizes=(58, 60, 40), max_iter=500,
                              random_state=42))])