In [17]:
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris()
X = iris.data
y = iris.target
target_names = iris.target_names

In [2]:
X_centered = X - np.mean(X, axis=0)

cov_matrix = np.cov(X_centered, rowvar=False)

In [3]:
cov_matrix

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [4]:
eig_vals, eig_vecs = np.linalg.eigh(cov_matrix)

In [5]:
eig_vals, eig_vecs

(array([0.02383509, 0.0782095 , 0.24267075, 4.22824171]),
 array([[ 0.31548719,  0.58202985,  0.65658877, -0.36138659],
        [-0.3197231 , -0.59791083,  0.73016143,  0.08452251],
        [-0.47983899, -0.07623608, -0.17337266, -0.85667061],
        [ 0.75365743, -0.54583143, -0.07548102, -0.3582892 ]]))

In [20]:
import numpy as np

class PCAclass:
    def __init__(self, n_components):
        self.n_components = n_components
        self.components_ = None
        self.mean_ = None
        self.explained_variance_ = None
        self.explained_variance_ratio_ = None

    def fit(self, X):
        # 1. Center the data
        self.mean_ = np.mean(X, axis=0)
        X_centered = X - self.mean_

        # 2. Covariance matrix
        cov_matrix = np.cov(X_centered, rowvar=False)

        # 3. Eigen decomposition
        eig_vals, eig_vecs = np.linalg.eigh(cov_matrix)

        # 4. Sort eigenvalues (descending)
        sorted_idx = np.argsort(eig_vals)[::-1]
        eig_vals = eig_vals[sorted_idx]
        eig_vecs = eig_vecs[:, sorted_idx]

        # 5. Select first n_components
        self.components_ = eig_vecs[:, :self.n_components]

        # 6. Save explained variance info
        self.explained_variance_ = eig_vals[:self.n_components]
        self.explained_variance_ratio_ = eig_vals[:self.n_components] / np.sum(eig_vals)

    def transform(self, X):
        X_centered = X - self.mean_
        return np.dot(X_centered, self.components_)

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)


In [61]:
# Fake dataset
X = np.random.rand(100, 5)

pca = PCAclass(n_components=2)
X_reduced = pca.fit_transform(X)

print("Original shape:", X.shape)
print("Reduced shape:", X_reduced.shape)
print("Explained variance ratio:", pca.explained_variance_ratio_)

Original shape: (100, 5)
Reduced shape: (100, 2)
Explained variance ratio: [0.26946592 0.24511253]


In [6]:
X_centered = X - np.mean(X, axis=0)

In [10]:
X_centered.shape

(150, 4)

In [8]:
U, S, Vt = np.linalg.svd(X_centered, full_matrices=False)

In [54]:
Vt

array([[ 0.36138659, -0.08452251,  0.85667061,  0.3582892 ],
       [-0.65658877, -0.73016143,  0.17337266,  0.07548102],
       [ 0.58202985, -0.59791083, -0.07623608, -0.54583143],
       [ 0.31548719, -0.3197231 , -0.47983899,  0.75365743]])

In [15]:
import numpy as np

class PCAclassSVD:
    def __init__(self, n_components):
        self.n_components = n_components
        self.components_ = None
        self.mean_ = None
        self.explained_variance_ = None
        self.explained_variance_ratio_ = None

    def fit(self, X):
        # 1. Center the data
        self.mean_ = np.mean(X, axis=0)
        X_centered = X - self.mean_

        # 2. SVD
        U, S, Vt = np.linalg.svd(X_centered, full_matrices=False)

        # 3. Components (asosiy yo‘nalishlar)
        self.components_ = Vt[:self.n_components].T

        # 4. Explained variance (S^2 / (n_samples - 1))
        n_samples = X.shape[0]
        eig_vals = (S**2) / (n_samples - 1)

        self.explained_variance_ = eig_vals[:self.n_components]
        self.explained_variance_ratio_ = eig_vals[:self.n_components] / np.sum(eig_vals)

    def transform(self, X):
        X_centered = X - self.mean_
        return np.dot(X_centered, self.components_)

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)


In [51]:
# Fake dataset
X = np.random.rand(100, 5)

pca = PCAclassSVD(n_components=2)
X_reduced = pca.fit_transform(X)

print("Original shape:", X.shape)
print("Reduced shape:", X_reduced.shape)
print("Explained variance ratio:", pca.explained_variance_ratio_)


Original shape: (100, 5)
Reduced shape: (100, 2)
Explained variance ratio: [0.26518625 0.21395762]


In [68]:
X = np.random.rand(100, 5)

In [75]:
from sklearn.decomposition import PCA


pca = PCA(n_components=2)
X_reduced = pca.fit_transform(X)

print("Original shape:", X.shape)
print("Reduced shape:", X_reduced.shape)
print("Explained variance ratio:", pca.explained_variance_ratio_)

Original shape: (100, 5)
Reduced shape: (100, 2)
Explained variance ratio: [0.23877574 0.21337459]
